#!/bin/sh

# Only enable /lib overlay if non-stock kernel
KERNEL_RELEASE=$(uname -r)
if [ "$KERNEL_RELEASE" != "3.8.13-mrvl" ]; then
  echo "Enabling /lib overlay."
  mkdir -p /mnt/config/overlay/lib
  mount -t unionfs -o dirs=/mnt/config/overlay/lib=rw:/lib=ro unionfs /lib
fi

